### ISSUE TITLE
Non asci characters

### ISSUE THREAD

**Issue by fondberg** [mathertel/LiquidCrystal_PCF8574#8]
Thanks for a great library! It was the only one which worked with my display.
I want to display characters with umlauts which are not in the asci character set. Do you know how to do that?
Example: 
`  lcd.print("ä ö");`

**Comment by mathertel** [comment]
you must create the characters bitmap and then upload these to the 8 special characters.
See createChar() function and samples you can find on the internet.

because all characters will come through the write function of the library you can modify this function in the library for you to replace ascii umlaute to these special characters.
